import React from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import Home from './pages/Home';
import Navbar from './components/Navbar';
import Login from './pages/Login';
import Register from './pages/Register';
import Profile from './pages/Profile';
import Sidebar from './components/Layout/Sidebar';
import Artisans from './pages/Artisans';
import Bookings from './pages/Bookings';
import Admin from './pages/Admin';
import './App.css';